### ISSUE TITLE
입력된 글자의 정답/오답 유무를 색상으로 표현하는 기능

### ISSUE THREAD

**Issue by ParkYoungWoong** [nodeHero/ggamji#6]
# 입력된 글자의 정답/오답 유무를 색상으로 표현하는 기능

### 기능
  1. 사용자에게 입력되는 마지막 단어(1글자)의 색상을 변경
  1. 정답인 경우 '초록색' 으로 변경
  1. 오답인 경우 '빨간색' 으로 변경

### 진행된 방법
  1. 사용자에게 `input` 요소로 데이터를 입력 받음
  1. `input` 요소에 입력된 단어를 '배열' 로 변경
  1. 1글자씩 색상을 변경할 수 있도록 '배열' 정보에 맞게 DOM 생성
  1. '배열' 정보의 마지막 단어를 정답과 비교하여 정답 유무 판단
  1. 정답 유무에 따라 색상 변경

### 문제점
  1. 사용자에게 입력받는 데이터와 생성되는(시각적으로 보여질) DOM 사이의 속도 차이 문제
  1. 입력받은 데이터와 생성된 DOM 이 다른 문제

### 추후 해결방안
  1. Code 최적화로 속도 차이 해결
  1. 비동기(?)

**Comment by ParkYoungWoong** [comment]
### 차선책
완성된 단어가 맞을 경우에만 전체의 색상을 '초록색'(정답 색상)으로 변경

**Comment by BK-Choi** [comment]
틀린경우 글씨가 흔들리는 것으로 변경
